# To build, run this from the main folder:
# docker image build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) --file Dockerfile.txt --tag lonce:transformerlw .

FROM nvcr.io/nvidia/pytorch:22.05-py3

# create a project directory inside user home
ENV PROJECT_DIR=/working
RUN mkdir $PROJECT_DIR
WORKDIR $PROJECT_DIR

COPY . $WORKDIR

RUN apt update && apt install -y git
RUN pip install --upgrade --ignore-installed "llvmlite<0.37,>=0.36.0rc1"

# install the packages
RUN pip install -r requirements.txt
#install the local copy of vampnet
# RUN pip install .   

WORKDIR /transformerlw

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user
USER user

# 
ENTRYPOINT ["/usr/bin/bash"]
#CMD ["bash"]

# to run (and use /scratch as for data and checkpoints):
# docker run --ipc=host --gpus "device=0" -it -v $(pwd):/vampnet  -v /scratch:/scratch --rm lonce:vampnet
