experiment: "mini_test_01"

data_dir: "testdata/dac-train"
data_frames: "testdata/dac-train.xlsx"
validator_data_dir: "testdata/dac-val"
validator_data_frames: "testdata/dac-val.xlsx"


TransformerClass: "RopeCondDACTransformer" 
vocab_size: 1024
num_tokens: 4

cond_params: 1 #1 (not counting the classes)
model_size: 32 # must be divisible by num_heads
# tblock_input_size: 35 #512  #embedding+conditioning vect

Ti: 86 # 172 #86
Tt: 430 # must match the length of the sequences in the batch
batch_size: 4  #**


num_layers: 2 #**
num_heads: 2 #8 # 8 # embed_size must be divisible by num_heads
forward_expansion: 2 #4 #4
dropout_rate: 0.2
learning_rate: 0.0005

num_epochs: 10 ### 800 

ErrorLogRate: 2 ### 10
checkpoint_interval: 5 ###50 # 25

